<?php

use App\Helpers\Pagination;
use App\Helpers\Utils;

$idlista = $this->view->idlista;

$pagination = Pagination::make($this, function ($btn, $controllerName) use ($idlista) {
    return [
        'previous' => "{$controllerName}detalhar/idlista/{$idlista}/pagina/{$btn['previous']}",
        'next' => "{$controllerName}detalhar/idlista/{$idlista}/pagina/{$btn['next']}",
        'current' => "{$controllerName}detalhar/idlista/{$idlista}/pagina/" . Pagination::CURRENT_PAGE
    ];
});

?>
<div class="modal fade" id="modalLiquidarAction">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Liquidar Solicitação</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="<?= $this->view->controller; ?>liquidarNf" method="post">
                <div class="modal-body">
                    <input type="hidden" name="invoice_id" id="invoice_id" />
                    <input type="hidden" name="request_id" id="request_id" />
                    <div class="form-group">
                        <label>Número da NS</label>
                        <input
                            type=text
                            id="number_request"
                            name="number_request"
                            placeholder="Digite o número da NS"
                            class="form-control"
                            required/>
                    </div>
                    <div class="form-group">
                        <label>Data do documento</label>
                        <input
                            type=text
                            id="date_document"
                            name="date_document"
                            class="form-control"
                            placeholder="Data no formato DD-MM-AAAA"
                            data-mask="00-00-0000"
                            required/>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button class="btn btn-primary float-right"><i class="fa fa-check"></i> Confirmar</button>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="modal fade" id="modalPagarAction">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Pagar Solicitação</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="<?= $this->view->controller; ?>pagarNf" method="post">
                <div class="modal-body">
                    <input type="hidden" name="invoice_id" id="invoice_pagar_id" />
                    <input type="hidden" name="request_id" id="request_pagar_id" />
                    <div class="form-group">
                        <label>Número da Ordem Bancária (OB)</label>
                        <input
                            type=text
                            id="order_bank"
                            name="order_bank"
                            placeholder="Digite o número da OB"
                            class="form-control"
                            required/>
                    </div>
                    <div class="form-group">
                        <label>Data do documento</label>
                        <input
                            type=text
                            id="date_document"
                            name="date_document"
                            class="form-control"
                            placeholder="Data no formato DD-MM-AAAA"
                            data-mask="00-00-0000"
                            required/>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button class="btn btn-primary float-right"><i class="fa fa-check"></i> Confirmar</button>
                </div>
            </form>
        </div>
    </div>
</div>
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5>Pedidos do Empenho</h5>
                <?php if (isset($this->view->resultEmpenho['code'])) : ?>
                    <div class="alert alert-info" role="alert">
                        Número do empenho: <strong><?= $this->view->resultEmpenho['code']; ?></strong><br>
                        OM: <strong><?= $this->view->resultEmpenho['naval_indicative']; ?></strong><br>
                        Status: <strong><?= $this->view->resultEmpenho['status']; ?></strong><br>
                    </div>
                <?php endif; ?>
                <div id="resultado"></div>
                <form action="<?= $this->view->controller ?>registraItensEmpenho" method="post" id="form">
                    <input type="hidden" name="code_invoice" value="<?= $this->view->resultEmpenho['code']; ?>">
                    <?php if (in_array($this->view->userLoggedIn['level'], ['ENCARREGADO', 'NORMAL', 'ADMINISTRADOR'])) : ?>
                        <button class="btn btn-primary">
                            <i class="fa fa-check"></i> Gerar solicitação
                        </button>
                    <?php endif ?>
                    <p class="help-block" style="color: #130f0f; font-weight: bold;">* Informe a quantidade para gerar a solicitação.</p>
                    <a href="<?= $this->view->controller; ?>" class="btn btn-warning pull-right">
                        <i class="fa fa-arrow-left"></i> Voltar
                    </a>
                    <div class="row" style="margin-bottom: 10px; margin-top: 10px;">
                        <div class="col-md-12">
                            <i class="fa fa-list"></i> <?= $this->view->title; ?>
                        </div>
                    </div>
                    <?= $pagination; ?>
                    <table class="table">
                        <thead>
                            <tr>
                                <?php if (in_array($this->view->userLoggedIn['level'], ['ENCARREGADO', 'NORMAL', 'ADMINISTRADOR'])) : ?>
                                <th width="8%">Quantidade</th>
                                <?php endif ?>
                                <th>Item</th>
                                <th>Empenhado</th>
                                <th>Solicitado</th>
                                <th>Entregue</th>
                                <th>Disponível</th>
                                <th>UF</th>
                                <th>Nome</th>
                                <th>Valor (R$)</th>
                                <th>Subtotal</th>
                                <th>Subtotal Disponível</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            $total = 0;
                            $totalDisponivel = 0;
                            foreach ($this->view->result as $value) :
                                $subTotal = $value['value'] * $value['quantity'];
                                $total += $subTotal;
                                $totalDisponivel += ($value['value'] * $value['quantity']) - ($value['value'] * $value['delivered']);
                                $qtdDisponivel = $value['quantity'] - ($value['delivered'] + $value['requested']);
                            ?>
                                <tr>
                                    <?php if (in_array($this->view->userLoggedIn['level'], ['ENCARREGADO', 'NORMAL', 'ADMINISTRADOR'])) : ?>
                                        <td>
                                            <input type="hidden" name="ids[]" value="<?= $value['id']; ?>" 
                                            <?= ($qtdDisponivel <= 0) ? 'disabled' : '' ?>>
                                            <input type="hidden" name="requested[]" id="requested[]" value="<?= $value['requested'] ?>"
                                            <?= ($qtdDisponivel <= 0) ? 'disabled' : '' ?>>
                                            <input type="hidden" name="delivered[]" value="<?= intval($value['delivered']); ?>"
                                            <?= ($qtdDisponivel <= 0) ? 'disabled' : '' ?>>
                                            <input type="text" name="quantity[]" id="quantity" class="form-control"
                                            <?= ($qtdDisponivel <= 0) ? 'disabled' : '' ?>>
                                        </td>
                                    <?php endif; ?>
                                    <td><?= $value['number'] ?: ''; ?></td>
                                    <td><?= floatval($value['quantity']); ?></td>
                                    <td><?= floatval($value['requested']); ?></td>
                                    <td><?= intval($value['delivered']); ?></td>
                                    <td>
                                        <span class="badge badge-primary">
                                            <?= floatval($qtdDisponivel); ?>
                                        </span>
                                    </td>
                                    <td><?= $value['uf']; ?></td>
                                    <td><?= $value['name']; ?></td>
                                    <td><?= Utils::floatToMoney($value['value']); ?></td>
                                    <td><?= Utils::floatToMoney($subTotal); ?></td>
                                    <td><?= Utils::floatToMoney($subTotal - ($value['value'] * $value['delivered'])); ?></td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                        <tfoot>
                            <tr>
                                <th class="text-right" colspan="9">Total (R$)</th>
                                <td class="text-left">
                                    <span class="badge badge-danger">
                                        <?= Utils::floatToMoney($total); ?>
                                    </span>
                                </td>
                                <td class="text-left">
                                    <span class="badge badge-danger">
                                        <?= Utils::floatToMoney($totalDisponivel); ?>
                                    </span>
                                </td>
                            </tr>
                        </tfoot>
                    </table>
                </form>
                <?= $pagination; ?>

                <?php
                $request = 0;
                foreach ($this->view->resultItems as $result) :
                    if ($request == $result['code']) {
                        continue;
                    }
                ?>
                    <div class="accordion">
                        <div class="card">
                            <div class="card-header" id="headingOne">
                                <h5 class="mb-0">
                                    <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne<?= $result['code'] ?>" aria-expanded="true" aria-controls="collapseOne">
                                        Solicitação a empresa nº <?= substr($result['code'], -1) ?> do Empenho <?= $this->view->resultEmpenho['code'] ?>
                                    </button>
                                </h5>
                            </div>
                            <div id="collapseOne<?= $result['code'] ?>" class="collapse">
                                <div class="card-body">
                                <?php if (isset($result['invoice']) || isset($result['number_request']) || isset($result['number_order_bank'])) : ?>
                                    <div class="alert alert-info" role="alert">
                                        NF: <strong><?= $result['invoice'] ?? '-'; ?></strong><br>
                                        NS: <strong><?= $result['number_request'] ?? '-'; ?><?= ($result['number_request_date']) ? ' - ' . date('d-m-Y', strtotime($result['number_request_date'])) : '' ?></strong><br>
                                        OB: <strong><?= $result['number_order_bank'] ?? '-'; ?><?= ($result['number_order_bank_date']) ? ' - ' . date('d-m-Y', strtotime($result['number_order_bank_date'])) : '' ?></strong><br>
                                        <?php if ($result['observation']) : ?>
                                            Observações do recebimento: <strong><?= $result['observation']; ?></strong>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                                    <?php
                                    if ($result['code']) {
                                        $code = $result['code'];
                                    }
                                    ?>
                                    <a href="<?= $this->view->controller; ?>pdf/id/<?= $code ?>/idlista/<?= $idlista ?>" class="btn btn-secondary btn-sm">
                                        <i class="fa fa-file-pdf-o"></i> PDF
                                    </a>
                                    <?php if (isset($code) && in_array($this->view->userLoggedIn['level'], ['ENCARREGADO', 'NORMAL', 'ADMINISTRADOR']) && in_array($result['status'], ['SOLICITADO'])) : ?>
                                        <a href="<?= $this->view->controller; ?>receber/id/<?= $code ?>/idlista/<?= $idlista ?>" class="btn btn-success btn-sm">
                                            <i class="fa fa-check"></i> Receber
                                        </a>
                                    <?php endif; ?>
                                    <?php if (isset($code) && in_array($this->view->userLoggedIn['level'], ['ENCARREGADO', 'NORMAL', 'ADMINISTRADOR']) && $result['status'] == 'SOLICITADO') : ?>
                                        <a onclick="confirmar('Tem certeza que deseja CANCELAR este registro?', '<?= $this->view->controller; ?>cancela/id/<?= $code; ?>/idlista/<?= $idlista ?>')" class="btn btn-danger btn-sm">
                                            <i class="fa fa-ban"></i> Cancelar
                                        </a>
                                    <?php endif; ?>
                                    <?php if (isset($code) && in_array($this->view->userLoggedIn['level'], ['CONTROLADOR_FINANCA', 'ADMINISTRADOR']) && in_array($result['status'], ['RECEBIDO', 'RECEBIDO-PARCIAL'])) : ?>
                                        <a href="<?= $this->view->controller; ?>entregarNf/id/<?= $code ?>/idlista/<?= $idlista ?>" class="btn btn-success btn-sm">
                                            <i class="fa fa-check"></i> Entregar NF
                                        </a>
                                    <?php endif; ?>
                                    <?php if (isset($code) && in_array($this->view->userLoggedIn['level'], ['CONTROLADOR_FINANCA', 'ADMINISTRADOR']) && $result['status'] == 'NF-ENTREGUE') : ?>
                                        <button data-request="<?= $code ?>" data-invoice="<?= $idlista ?>" class="btn btn-success btn-sm btn-liquidar">
                                            <i class="fa fa-check-square-o"></i> Liquidar NF
                                        </button>
                                    <?php endif; ?>
                                    <?php if (isset($code) && in_array($this->view->userLoggedIn['level'], ['CONTROLADOR_FINANCA', 'ADMINISTRADOR']) && $result['status'] == 'NF-LIQUIDADA') : ?>
                                        <button data-request="<?= $code ?>" data-invoice="<?= $idlista ?>" class="btn btn-success btn-sm btn-pagar">
                                            <i class="fa fa-dollar"></i> Pagar NF
                                        </button>
                                    <?php endif; ?>
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>Nº</th>
                                                <th>Solicitado</th>
                                                <th>Entregue</th>
                                                <?php if ($result['status'] == 'SOLICITADO'): ?>
                                                <th>Disponível</th>
                                                <?php endif; ?>
                                                <th>Status</th>
                                                <th>UF</th>
                                                <th>Nome</th>
                                                <th>Valor (R$)</th>
                                                <th>Subtotal (R$)</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php
                                            $total = 0;
                                            foreach ($this->view->resultItems as $value) :
                                                if ($value['code'] != $result['code']) {
                                                    continue;
                                                }
                                                if ($result['status'] == 'SOLICITADO') {
                                                    $total += $value['value'] * $value['quantity'];
                                                } else {
                                                    $total += $value['value'] * $value['delivered'];
                                                }
                                            ?>
                                                <tr>
                                                    <td><?= substr($value['code'], -1); ?></td>
                                                    <td><?= floatval($value['quantity']); ?></td>
                                                    <td><?= intval($value['delivered']); ?></td>
                                                    <?php if ($result['status'] == 'SOLICITADO'): ?>
                                                    <td><?= floatval($value['quantity'] - $value['delivered']); ?></td>
                                                    <?php endif; ?>
                                                    <td><?= $value['status']; ?></td>
                                                    <td><?= $value['uf']; ?></td>
                                                    <td><?= $value['name']; ?></td>
                                                    <td><?= Utils::floatToMoney($value['value']); ?></td>
                                                    <?php if ($result['status'] == 'SOLICITADO'): ?>
                                                        <td><?= Utils::floatToMoney(($value['value'] * $value['quantity'])); ?></td>
                                                    <?php else : ?>
                                                        <td><?= Utils::floatToMoney(($value['value'] * $value['delivered'])); ?></td>
                                                    <?php endif; ?>
                                                </tr>
                                            <?php endforeach; ?>
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <th class="text-right" colspan="<?= ($result['status'] == 'SOLICITADO') ? 8 : 7 ?>">Total (R$)</th>
                                                <td class="text-left">
                                                    <span class="badge badge-danger">
                                                        <?= Utils::floatToMoney($total); ?>
                                                    </span>
                                                </td>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php
                    $request = $result['code'];
                endforeach; ?>
            </div>
        </div>
    </div>
</div>
<script>
    $('.btn-liquidar').click(function() {
        var requestId = $(this).attr('data-request');
        var invoiceId = $(this).attr('data-invoice');

        $('#request_id').val(requestId);
        $('#invoice_id').val(invoiceId);
        $('#modalLiquidarAction').modal('show');
    });
    $('.btn-pagar').click(function() {
        var requestId = $(this).attr('data-request');
        var invoiceId = $(this).attr('data-invoice');

        $('#request_pagar_id').val(requestId);
        $('#invoice_pagar_id').val(invoiceId);
        $('#modalPagarAction').modal('show');
    });
</script>