<?php

use App\Helpers\Pagination;
use App\Helpers\View;
use App\Helpers\Utils;

$pagination = Pagination::make($this, function ($btn, $controllerName) {
    return [
        'previous' => "{$controllerName}solicitacoes/pagina/{$btn['previous']}",
        'next' => "{$controllerName}solicitacoes/pagina/{$btn['next']}",
        'current' => "{$controllerName}solicitacoes/pagina/" . Pagination::CURRENT_PAGE
    ];
});

?>
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5>Solicitações das empresas</h5>
                <i class="fa fa-list"></i> <?= $this->view->title; ?>

                <div class="row">
                    <div class="col-md-6">
                        <?= $pagination; ?>
                    </div>
                    <div class="col-lg-6">
                        <form action="<?= $this->view->controller; ?>solicitacoes/pagina/<?= $this->view->btn['current']; ?>" class="search-form" onsubmit="return false">
                            <div class="input-group search-input-box">
                                <input type="text" class="form-control search-input" placeholder="Nº Empenho, Solicitação ou Status">
                                <span class="input-group-btn">
                                    <button class="btn btn-secondary search-button" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                        </form>
                    </div>
                </div>
                <?php
                $request = 0;
                foreach ($this->view->result as $result) :
                    $idlista = $result['invoices_id'];
                    if ($request == $result['code']) {
                        continue;
                    }
                ?>
                    <div class="accordion">
                        <div class="card">
                            <div class="card-header" id="headingOne">
                                <h5>
                                    <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne<?= $result['code'] ?>" aria-expanded="true" aria-controls="collapseOne">
                                        Solicitação <?= $result['code'] ?> do Empenho <?= $result['codeInvoice'] ?> - <span class="badge badge-primary"><?= $result['status']; ?></span>
                                    </button>
                                </h5>
                            </div>
                            <div id="collapseOne<?= $result['code'] ?>" class="collapse">
                                <div class="card-body">
                                    <?php
                                    if ($result['code']) {
                                        $code = $result['code'];
                                    }
                                    ?>
                                    <a href="<?= $this->view->controller; ?>pdf/id/<?= $code ?>" class="btn btn-secondary btn-sm">
                                        <i class="fa fa-file-pdf-o"></i> PDF
                                    </a>
                                    <?php if (isset($code) && in_array($result['status'], ['SOLICITADO'])) : ?>
                                        <a href="<?= $this->view->controller; ?>receber/id/<?= $code ?>/idlista/<?= $idlista ?>" class="btn btn-success btn-sm">
                                            <i class="fa fa-check"></i> Receber
                                        </a>
                                    <?php endif; ?>
                                    <?php if (isset($code) && $result['status'] == 'SOLICITADO') : ?>
                                        <a onclick="confirmar('Tem certeza que deseja CANCELAR este registro?', '<?= $this->view->controller; ?>cancela/id/<?= $code; ?>')" class="btn btn-danger btn-sm">
                                            <i class="fa fa-ban"></i> Cancelar
                                        </a>
                                    <?php endif; ?>
                                    <?php if (isset($code) && in_array($result['status'], ['RECEBIDO', 'RECEBIDO-PARCIAL'])) : ?>
                                        <a href="<?= $this->view->controller; ?>entregarNf/id/<?= $code ?>" class="btn btn-success btn-sm">
                                            <i class="fa fa-check"></i> Entregar NF
                                        </a>
                                    <?php endif; ?>
                                    <?php if (isset($code) && $result['status'] == 'NF-ENTREGUE') : ?>
                                        <a href="<?= $this->view->controller; ?>liquidarNf/id/<?= $code ?>" class="btn btn-success btn-sm">
                                            <i class="fa fa-check-square-o"></i> Liquidar NF
                                        </a>
                                    <?php endif; ?>
                                    <?php if (isset($code) && $result['status'] == 'NF-LIQUIDADA') : ?>
                                        <a href="<?= $this->view->controller; ?>pagarNf/id/<?= $code ?>" class="btn btn-success btn-sm">
                                            <i class="fa fa-dollar"></i> Pagar NF
                                        </a>
                                    <?php endif; ?>
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>Nº</th>
                                                <th>Solicitado</th>
                                                <th>Entregue</th>
                                                <th>Disponível</th>
                                                <th>Status</th>
                                                <th>UF</th>
                                                <th>Nome</th>
                                                <th>Valor (R$)</th>
                                                <th>Subtotal (R$)</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php
                                            $total = 0;
                                            foreach ($this->view->result as $value) :
                                                if ($value['code'] != $result['code']) {
                                                    continue;
                                                }
                                                $total += $value['value'] * $value['quantity'];
                                            ?>
                                                <tr>
                                                    <td><?= $value['code'] ?: ''; ?></td>
                                                    <td><?= floatval($value['quantity']); ?></td>
                                                    <td><?= intval($value['delivered']); ?></td>
                                                    <td><?= floatval($value['quantity'] - $value['delivered']); ?></td>
                                                    <td><?= $value['status']; ?></td>
                                                    <td><?= $value['uf']; ?></td>
                                                    <td><?= $value['name']; ?></td>
                                                    <td><?= Utils::floatToMoney($value['value']); ?></td>
                                                    <td><?= Utils::floatToMoney(($value['value'] * $value['quantity'])); ?></td>
                                                </tr>
                                            <?php endforeach; ?>
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <th class="text-right" colspan="8">Total (R$)</th>
                                                <td class="text-left">
                                                    <span class="badge badge-danger">
                                                        <?= Utils::floatToMoney($total); ?>
                                                    </span>
                                                </td>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php
                    $request = $result['code'];
                endforeach; ?>

            </div>
        </div>
    </div>
</div>
<script>
    $('.search-button').click(function btnSearch() {
        var searchInput = $('.search-input');
        var searchValue = searchInput.val();
        var formAction = $('.search-form').attr('action');
        if (searchValue && formAction) {
            window.location = formAction + '/busca/' + searchValue;
        } else {
            searchInput.focus();
        }
    });
</script>