<?php

use App\Helpers\Pagination;
use App\Helpers\View;
use App\Helpers\Utils;

$pagination = Pagination::make($this, function ($btn, $controllerName) {
    return [
        'previous' => "{$controllerName}solicitacoes/pagina/{$btn['previous']}",
        'next' => "{$controllerName}solicitacoes/pagina/{$btn['next']}",
        'current' => "{$controllerName}solicitacoes/pagina/" . Pagination::CURRENT_PAGE
    ];
});

?>
<div class="modal fade" id="modalEntregarAction">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Entregar Nota fiscal</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="<?= $this->view->controller; ?>entregarNf" method="post">
                <div class="modal-body">
                    <input type="hidden" name="invoice_id" id="invoice_entregar_id" />
                    <input type="hidden" name="request_id" id="request_entregar_id" />
                    <div class="form-group">
                        <label>Data do documento</label>
                        <input
                            type=text
                            id="date_document"
                            name="date_document"
                            class="form-control"
                            placeholder="Data no formato DD-MM-AAAA"
                            data-mask="00-00-0000"
                            data-mask-reverse="true"
                            required/>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button class="btn btn-primary float-right"><i class="fa fa-check"></i> Confirmar</button>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="modal fade" id="modalLiquidarAction">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Liquidar Solicitação</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="<?= $this->view->controller; ?>liquidarNf" method="post">
                <div class="modal-body">
                    <div id="resultado"></div>
                    <input type="hidden" name="invoice_id" id="invoice_id" />
                    <input type="hidden" name="request_id" id="request_id" />
                    <div class="form-group">
                        <label>Número da NS</label>
                        <input
                            type=text
                            id="number_request"
                            name="number_request"
                            placeholder="Digite o número da NS"
                            class="form-control"
                            required/>
                    </div>
                    <div class="form-group">
                        <label>Data do documento</label>
                        <input
                            type=text
                            id="date_document"
                            name="date_document"
                            class="form-control"
                            placeholder="Data no formato DD-MM-AAAA"
                            data-mask="00-00-0000"
                            data-mask-reverse="true"
                            required/>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button class="btn btn-primary float-right"><i class="fa fa-check"></i> Confirmar</button>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="modal fade" id="modalPagarAction">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Pagar Solicitação</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="<?= $this->view->controller; ?>pagarNf" method="post">
                <div class="modal-body">
                    <div id="resultado"></div>
                    <input type="hidden" name="invoice_id" id="invoice_pagar_id" />
                    <input type="hidden" name="request_id" id="request_pagar_id" />
                    <div class="form-group">
                        <label>Número da Ordem Bancária (OB)</label>
                        <input
                            type=text
                            id="order_bank"
                            name="order_bank"
                            placeholder="Digite o número da OB"
                            class="form-control"
                            required/>
                    </div>
                    <div class="form-group">
                        <label>Data do documento</label>
                        <input
                            type=text
                            id="date_document"
                            name="date_document"
                            class="form-control"
                            placeholder="Data no formato DD-MM-AAAA"
                            data-mask="00-00-0000"
                            data-mask-reverse="true"
                            required/>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button class="btn btn-primary float-right"><i class="fa fa-check"></i> Confirmar</button>
                </div>
            </form>
        </div>
    </div>
</div>
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5>Solicitações das empresas</h5>
                <i class="fa fa-list"></i> <?= $this->view->title; ?>

                <div class="row">
                    <div class="col-md-6">
                        <?= $pagination; ?>
                    </div>
                    <div class="col-lg-6">
                        <form action="<?= $this->view->controller; ?>solicitacoes/pagina/<?= $this->view->btn['current']; ?>" class="search-form" onsubmit="return false">
                            <div class="input-group search-input-box">
                                <input type="text" class="form-control search-input" placeholder="Nº Empenho, OM, Solicitação ou Status">
                                <span class="input-group-btn">
                                    <button class="btn btn-secondary search-button" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                        </form>
                    </div>
                </div>
                <?php
                $request = 0;
                foreach ($this->view->result as $result) :
                    $idlista = $result['invoices_id'];
                    if ($request == $result['code']) {
                        continue;
                    }
                ?>
                    <div class="accordion">
                        <div class="card">
                            <div class="card-header" id="headingOne">
                                <h5>
                                    <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne<?= $result['code'] ?>" aria-expanded="true" aria-controls="collapseOne">
                                        Solicitação a empresa nº <?= substr($result['code'], -1); ?> do Empenho <?= $result['codeInvoice'] ?> - <?= $result['naval_indicative'] ?> - <span class="badge badge-primary"><?= $result['status']; ?></span>
                                    </button>
                                </h5>
                            </div>
                            <div id="collapseOne<?= $result['code'] ?>" class="collapse">
                                <div class="card-body">
                                <?php if (isset($result['invoice']) || isset($result['number_request']) || isset($result['number_order_bank'])) : ?>
                                    <div class="alert alert-info" role="alert">
                                        NF: <strong><?= $result['invoice'] ?? '-'; ?><?= ($result['invoice_date']) ? ' - ' . date('d-m-Y', strtotime($result['invoice_date'])) : '' ?></strong><br>
                                        NS: <strong><?= $result['number_request'] ?? '-'; ?><?= ($result['number_request_date']) ? ' - ' . date('d-m-Y', strtotime($result['number_request_date'])) : '' ?></strong><br>
                                        OB: <strong><?= $result['number_order_bank'] ?? '-'; ?><?= ($result['number_order_bank_date']) ? ' - ' . date('d-m-Y', strtotime($result['number_order_bank_date'])) : '' ?></strong><br>
                                        <?php if ($result['observation']) : ?>
                                            Observações do recebimento: <strong><?= $result['observation']; ?></strong>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                                    <?php
                                    if ($result['code']) {
                                        $code = $result['code'];
                                    }
                                    ?>
                                    <a href="<?= $this->view->controller; ?>pdf/id/<?= $code ?>/idlista/<?= $idlista ?>" class="btn btn-secondary btn-sm">
                                        <i class="fa fa-file-pdf-o"></i> PDF
                                    </a>
                                    <?php if (isset($code) && in_array($this->view->userLoggedIn['level'], ['ENCARREGADO', 'NORMAL', 'ADMINISTRADOR']) && in_array($result['status'], ['SOLICITADO'])) : ?>
                                        <a href="<?= $this->view->controller; ?>receber/id/<?= $result['code'] ?>/idlista/<?= $idlista ?>" class="btn btn-success btn-sm">
                                            <i class="fa fa-check"></i> Receber
                                        </a>
                                    <?php endif; ?>
                                    <?php if (isset($code) && in_array($this->view->userLoggedIn['level'], ['ENCARREGADO', 'NORMAL', 'ADMINISTRADOR']) && $result['status'] == 'SOLICITADO') : ?>
                                        <a onclick="confirmar('Tem certeza que deseja CANCELAR este registro?', '<?= $this->view->controller; ?>cancela/id/<?= $code; ?>/idlista/<?= $idlista ?>')" class="btn btn-danger btn-sm">
                                            <i class="fa fa-ban"></i> Cancelar
                                        </a>
                                    <?php endif; ?>
                                    <?php if (isset($code) && in_array($this->view->userLoggedIn['level'], ['CONTROLADOR_FINANCA', 'ADMINISTRADOR']) && in_array($result['status'], ['RECEBIDO', 'RECEBIDO-PARCIAL'])) : ?>
                                        <button data-request="<?= $code ?>" data-invoice="<?= $idlista ?>" class="btn btn-success btn-sm btn-entregar">
                                            <i class="fa fa-check"></i> Entregar NF
                                        </button>
                                    <?php endif; ?>
                                    <?php if (isset($code) && in_array($this->view->userLoggedIn['level'], ['CONTROLADOR_FINANCA', 'ADMINISTRADOR']) && $result['status'] == 'NF-ENTREGUE') : ?>
                                        <button data-request="<?= $code; ?>" data-invoice="<?= $idlista ?>" class="btn btn-success btn-sm btn-liquidar">
                                            <i class="fa fa-check-square-o"></i> Liquidar NF
                                        </button>
                                    <?php endif; ?>
                                    <?php if (isset($code) && in_array($this->view->userLoggedIn['level'], ['CONTROLADOR_FINANCA', 'ADMINISTRADOR']) && $result['status'] == 'NF-LIQUIDADA') : ?>
                                        <button data-request="<?= $code; ?>" data-invoice="<?= $idlista ?>" class="btn btn-success btn-sm btn-pagar">
                                            <i class="fa fa-dollar"></i> Pagar NF
                                        </button>
                                    <?php endif; ?>
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>Nº</th>
                                                <th>Solicitado</th>
                                                <th>Entregue</th>
                                                <?php if ($result['status'] == 'SOLICITADO'): ?>
                                                <th>Disponível</th>
                                                <?php endif; ?>
                                                <th>Status</th>
                                                <th>UF</th>
                                                <th>Nome</th>
                                                <th>Valor (R$)</th>
                                                <th>Subtotal (R$)</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php
                                            $total = 0;
                                            foreach ($this->view->result as $value) :
                                                if ($value['code'] != $result['code']) {
                                                    continue;
                                                }
                                                if ($result['status'] == 'SOLICITADO') {
                                                    $total += $value['value'] * $value['quantity'];
                                                } else {
                                                    $total += $value['value'] * $value['delivered'];
                                                }
                                            ?>
                                                <tr>
                                                    <td><?= substr($value['code'], -1); ?></td>
                                                    <td><?= floatval($value['quantity']); ?></td>
                                                    <td><?= floatval($value['delivered']); ?></td>
                                                    <?php if ($result['status'] == 'SOLICITADO'): ?>
                                                    <td><?= floatval($value['quantity'] - $value['delivered']); ?></td>
                                                    <?php endif; ?>
                                                    <td><?= $value['status']; ?></td>
                                                    <td><?= $value['uf']; ?></td>
                                                    <td><?= $value['name']; ?></td>
                                                    <td><?= Utils::floatToMoney($value['value']); ?></td>
                                                    <?php if ($result['status'] == 'SOLICITADO'): ?>
                                                        <td><?= Utils::floatToMoney(($value['value'] * $value['quantity'])); ?></td>
                                                    <?php else : ?>
                                                        <td><?= Utils::floatToMoney(($value['value'] * $value['delivered'])); ?></td>
                                                    <?php endif; ?>
                                                </tr>
                                            <?php endforeach; ?>
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <th class="text-right" colspan="<?= ($result['status'] == 'SOLICITADO') ? 8 : 7 ?>">Total (R$)</th>
                                                <td class="text-left">
                                                    <span class="badge badge-danger">
                                                        <?= Utils::floatToMoney($total); ?>
                                                    </span>
                                                </td>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php
                    $request = $result['code'];
                endforeach; ?>

            </div>
        </div>
    </div>
</div>
<script>
    $('.search-button').click(function btnSearch() {
        var searchInput = $('.search-input');
        var searchValue = searchInput.val();
        var formAction = $('.search-form').attr('action');
        if (searchValue && formAction) {
            window.location = formAction + '/busca/' + searchValue;
        } else {
            searchInput.focus();
        }
    });
    $('.btn-entregar').click(function() {
        var requestId = $(this).attr('data-request');
        var invoiceId = $(this).attr('data-invoice');

        $('#request_entregar_id').val(requestId);
        $('#invoice_entregar_id').val(invoiceId);
        $('#modalEntregarAction').modal('show');
    });
    $('.btn-liquidar').click(function() {
        var requestId = $(this).attr('data-request');
        var invoiceId = $(this).attr('data-invoice');

        $('#request_id').val(requestId);
        $('#invoice_id').val(invoiceId);
        $('#modalLiquidarAction').modal('show');
    });
    $('.btn-pagar').click(function() {
        var requestId = $(this).attr('data-request');
        var invoiceId = $(this).attr('data-invoice');

        $('#request_pagar_id').val(requestId);
        $('#invoice_pagar_id').val(invoiceId);
        $('#modalPagarAction').modal('show');
    });
</script>