<?php

use App\Helpers\Pagination;
use App\Helpers\View;
use App\Helpers\Utils;

$pagination = Pagination::make($this);

?>
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5>Relatório</h5>
                <i class="fa fa-list"></i> <?= $this->view->title; ?>
                <div id="resultado"></div>
                <div class="row">
                    <div class="col-md-7">
                        <?= $pagination; ?>
                    </div>

                    <div class="col-lg-5">
                        <form action="<?= $this->view->controller; ?>ver/pagina/<?= $this->view->btn['current']; ?>" class="search-form" onsubmit="return false">
                            <div class="input-group search-input-box">
                                <input type="text" class="form-control search-input" placeholder="Nº Empenho, OM, Status ou Data (DD-MM-YYYY)">
                                <span class="input-group-btn">
                                    <button class="btn btn-secondary search-button" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                        </form>
                    </div>
                </div>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Nº.</th>
                            <th>OM</th>
                            <th>Complemento</th>
                            <th>Total Solicitado</th>
                            <th>Total Recebido</th>
                            <th>Total Disponível</th>
                            <th>Status</th>
                            <th>Data de criação</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->result as $value) : ?>
                            <tr>
                                <td><strong><?= $value['code']; ?></strong></td>
                                <td><?= $value['naval_indicative']; ?></td>
                                <td><?= $value['complement']; ?></td>
                                <td><?= Utils::floatToMoney($value['quantity'] * $value['value']); ?></td>
                                <td><?= Utils::floatToMoney($value['delivered'] * $value['value']); ?></td>
                                <td><?= Utils::floatToMoney(($value['quantity'] * $value['value']) - ($value['delivered'] * $value['value'])); ?></td>
                                <td><?= $value['status']; ?></td>
                                <td>
                                    <span class="badge badge-danger">
                                        <?= View::humanDate(($value['created_at']) ? $value['created_at'] : date('Y-m-d', time())); ?>
                                    </span>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <?= $pagination; ?>
            </div>
        </div>
    </div>
</div>
<script>
    $('.search-button').click(function btnSearch() {
        var searchInput = $('.search-input');
        var searchValue = searchInput.val();
        var formAction = $('.search-form').attr('action');
        if (searchValue && formAction) {
            window.location = formAction + '/busca/' + searchValue;
        } else {
            searchInput.focus();
        }
    });
</script>