<?php

use App\Helpers\Pagination;
use App\Helpers\Utils;

$idlista = $this->view->idlista;

$pagination = Pagination::make($this, function ($btn, $controllerName) use ($idlista) {
    return [
        'previous' => "{$controllerName}detalhar/idlista/{$idlista}/pagina/{$btn['previous']}",
        'next' => "{$controllerName}detalhar/idlista/{$idlista}/pagina/{$btn['next']}",
        'current' => "{$controllerName}detalhar/idlista/{$idlista}/pagina/" . Pagination::CURRENT_PAGE
    ];
});

?>
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5>Pedidos do Empenho</h5>
                <?php if (isset($this->view->resultEmpenho['code'])) : ?>
                    <div class="alert alert-info" role="alert">
                        Número do empenho: <strong><?= $this->view->resultEmpenho['code']; ?></strong><br>
                        OM: <strong><?= $this->view->resultEmpenho['naval_indicative']; ?></strong><br>
                        Status: <strong><?= $this->view->resultEmpenho['status']; ?></strong><br>
                    </div>
                <?php endif; ?>
                <a href="<?= $this->view->controller; ?>" class="btn btn-warning pull-right">
                    <i class="fa fa-arrow-left"></i> Voltar
                </a>
                <div class="row" style="margin-bottom: 10px; margin-top: 10px;">
                    <div class="col-md-12">
                        <i class="fa fa-list"></i> <?= $this->view->title; ?>
                    </div>
                </div>
                <?= $pagination; ?>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Item</th>
                            <th>Empenhado</th>
                            <th>Solicitado</th>
                            <th>Disponível</th>
                            <th>UF</th>
                            <th>Nome</th>
                            <th>Valor (R$)</th>
                            <th>Subtotal (R$)</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $total = 0;
                        foreach ($this->view->result as $value):
                            $total += $value['value'] * $value['quantity'];
                        ?>
                            <tr>
                                <td><?= $value['number'] ?: ''; ?></td>
                                <td><?= floatval($value['quantity']); ?></td>
                                <td><?= intval($value['delivered']); ?></td>
                                <td><?= floatval($value['quantity_available']); ?></td>
                                <td><?= $value['uf']; ?></td>
                                <td><?= $value['name']; ?></td>
                                <td><?= Utils::floatToMoney($value['value']); ?></td>
                                <td><?= Utils::floatToMoney( ($value['value'] * $value['quantity']) ); ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                    <tfoot>
                        <tr>
                            <th class="text-right" colspan="7">Total (R$)</th>
                            <td class="text-left">
                                <span class="badge badge-danger">
                                    <?= Utils::floatToMoney($total); ?>
                                </span>
                            </td>
                        </tr>
                    </tfoot>
                </table>
                <?= $pagination; ?>

                <div class="accordion" id="accordionExample">
                    <div class="card">
                        <div class="card-header" id="headingOne">
                            <h5 class="mb-0">
                                <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                Enviar mensagem para OM <strong><?= $this->view->resultEmpenho['naval_indicative']; ?></strong>
                                </button>
                            </h5>
                        </div>
                        <div id="collapseOne" class="collapse">
                            <div class="card-body">
                                <div id="resultado"></div>
                                <form action="<?= $this->view->controller; ?>registra/" method="post" id="form">
                                    <input type="hidden" name="oms[]" value="<?= $this->view->resultEmpenho['oms_id']; ?>" />
                                    <div class="row" style="margin-top: 10px;">
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <label>Título</label>
                                                <input type="text"
                                                    id="title"
                                                    name="title"
                                                    placeholder="Título do aviso"
                                                    class="form-control"
                                                    required>
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>Data de Início</label>
                                                <input type="text"
                                                    id="beginning_date"
                                                    name="beginning_date"
                                                    placeholder="Data no formato DD-MM-YYYY"
                                                    class="form-control"
                                                    data-mask="00-00-0000"
                                                    required>
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>Data de Final</label>
                                                <input type="text"
                                                    id="ending_date"
                                                    name="ending_date"
                                                    placeholder="Data no formato DD-MM-YYYY"
                                                    class="form-control"
                                                    data-mask="00-00-0000"
                                                    required>
                                            </div>
                                        </div>
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <label>Mensagem</label>
                                                <textarea
                                                    maxlength="256"
                                                    name="content"
                                                    id="content"
                                                    class="form-control"
                                                    required></textarea>
                                                <p class="help-block">
                                                    <i class="fa fa-info-circle"></i> Mensagem com
                                                    <span class="text-danger">
                                                        256 caracteres
                                                    </span>
                                                </p>
                                            </div>
                                        </div>
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <button class="btn btn-primary"><i class="fa fa-check"></i> Enviar mensagem</button>
                                                <a href="<?= $this->view->controller; ?>" class="btn btn-warning"><i class="fa fa-arrow-left"></i> Voltar</a>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>