<?php

use App\Helpers\View;

$idlista = $this->view->idlista;

?>
<!-- Modal Empenho -->
<div class="modal fade" id="modalEmpenho">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Abater valor do Empenho</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="<?= $this->view->controller; ?>abaterValorEmpenho" method="post">
                <div class="modal-body">
                    <input type="hidden" name="id" value="<?= $this->view->resultEmpenho['id']; ?>" />
                    <div class="form-group">
                        <label>Valor que deseja cancelar:</label>
                        <input
                            type="text"
                            class="form-control"
                            id="value"
                            name="value"
                            placeholder="Valor para ser abatido do Empenho">
                    </div>
                    <div class="form-group">
                        <label>Observação:</label>
                        <textarea class="form-control" name="observation" placeholder="Adicione uma nota informando mais detalhes..."></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button class="btn btn-primary float-right"><i class="fa fa-check"></i> Registrar</button>
                </div>
            </form>
        </div>
    </div>
</div>
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5>Pedidos do Empenho</h5>
                <?php if (isset($this->view->resultEmpenho['code'])) : ?>
                    <div class="alert alert-info" role="alert">
                        Número do empenho: <strong><?= $this->view->resultEmpenho['code']; ?></strong><br>
                        OM: <strong><?= $this->view->resultEmpenho['naval_indicative']; ?></strong><br>
                        Total: <strong><?= $this->view->resultEmpenho['total']; ?></strong><br>
                        Status: <strong><?= $this->view->resultEmpenho['status']; ?></strong><br>
                    </div>
                <?php endif; ?>
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalEmpenho">
                    <i class="fa fa-edit"></i> Altenar Saldo do Empenho
                </button>
                <a href="<?= $this->view->controller; ?>" class="btn btn-warning pull-right">
                    <i class="fa fa-arrow-left"></i> Voltar
                </a>
                <div class="row" style="margin-bottom: 10px; margin-top: 10px;">
                    <div class="col-md-12">
                        <i class="fa fa-list"></i> <?= $this->view->title; ?>
                    </div>
                </div>
                <?= $pagination; ?>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Nº</th>
                            <th>OM</th>
                            <th>Fornecedor</th>
                            <th>NF</th>
                            <th>Tipo</th>
                            <th>Total</th>
                            <th>Status</th>
                            <th>Alteração</th>
                            <th>Entrega</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->resultPedidos as $value) : ?>
                            <tr>
                                <td><?= $value['number']; ?></td>
                                <td><?= $value['naval_indicative']; ?></td>
                                <td><?= View::limitString($value['suppliers_name'], 17); ?></td>
                                <td><?= $value['invoice'] ?: ''; ?></td>
                                <td>
                                    <?php if ($value['biddings_id']) : ?>
                                        <i class="fa fa-group"></i> LIC
                                    <?php else : ?>
                                        <i class="fa fa-shopping-cart"></i> NL
                                    <?php endif; ?>
                                </td>
                                <td><?= View::floatToMoney($value['total']) ?></td>
                                <td>
                                    <?= $value['status'] ?>
                                </td>
                                <td>
                                    <span class="badge badge-danger">
                                        <?= View::humanDate($value['updated_at']); ?>
                                    </span>
                                </td>
                                <td>
                                    <span class="badge badge-danger">
                                        <?= View::humanDate($value['delivery_date']); ?>
                                    </span>
                                </td>
                                <td>
                                    <a href="solicitacao/detalhar/idlista/<?= $value['id']; ?>" class="btn btn-primary btn-sm">
                                        <i class="fa fa-share"></i>
                                    </a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <?= $pagination; ?>

                <div class="accordion" id="accordionExample">
                    <div class="card">
                        <div class="card-header" id="headingOne">
                            <h5 class="mb-0">
                                <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                Enviar mensagem para OM <strong><?= $this->view->resultEmpenho['naval_indicative']; ?></strong>
                                </button>
                            </h5>
                        </div>
                        <div id="collapseOne" class="collapse">
                            <div class="card-body">
                                <div id="resultado"></div>
                                <form action="<?= $this->view->controller; ?>registra/" method="post" id="form">
                                    <input type="hidden" name="oms[]" value="<?= $this->view->resultEmpenho['oms_id']; ?>" />
                                    <div class="row" style="margin-top: 10px;">
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <label>Título</label>
                                                <input type="text"
                                                    id="title"
                                                    name="title"
                                                    placeholder="Título do aviso"
                                                    class="form-control"
                                                    required>
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>Data de Início</label>
                                                <input type="text"
                                                    id="beginning_date"
                                                    name="beginning_date"
                                                    placeholder="Data no formato DD-MM-YYYY"
                                                    class="form-control"
                                                    data-mask="00-00-0000"
                                                    required>
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>Data de Final</label>
                                                <input type="text"
                                                    id="ending_date"
                                                    name="ending_date"
                                                    placeholder="Data no formato DD-MM-YYYY"
                                                    class="form-control"
                                                    data-mask="00-00-0000"
                                                    required>
                                            </div>
                                        </div>
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <label>Mensagem</label>
                                                <textarea
                                                    maxlength="256"
                                                    name="content"
                                                    id="content"
                                                    class="form-control"
                                                    required></textarea>
                                                <p class="help-block">
                                                    <i class="fa fa-info-circle"></i> Mensagem com
                                                    <span class="text-danger">
                                                        256 caracteres
                                                    </span>
                                                </p>
                                            </div>
                                        </div>
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <button class="btn btn-primary"><i class="fa fa-check"></i> Enviar mensagem</button>
                                                <a href="<?= $this->view->controller; ?>" class="btn btn-warning"><i class="fa fa-arrow-left"></i> Voltar</a>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

                <?php if (isset($this->view->historico[0])): ?>
                <div class="accordion">
                    <div class="card">
                        <div class="card-header" id="headingOne">
                            <h5 class="mb-0">
                                <button
                                    class="btn btn-link"
                                    type="button"
                                    data-toggle="collapse"
                                    data-target="#collapseHistorico"
                                    aria-expanded="true"
                                    aria-controls="collapseHistorico">
                                    Histórico
                                </button>
                            </h5>
                        </div>
                        <div id="collapseHistorico" class="collapse">
                            <div class="card-body">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>Valor retirado</th>
                                            <th>Usuário responsável</th>
                                            <th>Observação</th>
                                            <th>Data</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($this->view->historico as $value) : ?>
                                            <tr>
                                                <td><?= View::floatToMoney($value['value']) ?></td>
                                                <td><?= $value['name']; ?></td>
                                                <td><?= $value['observation']; ?></td>
                                                <td>
                                                    <span class="badge badge-danger">
                                                        <?= View::humanDate($value['created_at']); ?>
                                                    </span>    
                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>