<?php

use App\Helpers\Pagination;
use App\Helpers\View;
use App\Config\Configurations as cfg;
use App\Helpers\Utils;

$idlista = $this->view->idlista;
$relativePathUploadFiles = 'arquivos' . cfg::DS . $this->view->resultSolicitacao['number'] . cfg::DS;
$fullPathUploadFiles = getcwd() . cfg::DS . $relativePathUploadFiles;
$pathSolemp = getcwd() . cfg::DS . 'arquivos' . cfg::DS . 'solemps' . cfg::DS;

$pagination = Pagination::make($this, function ($btn, $controllerName) use ($idlista) {
    return [
        'previous' => "{$controllerName}detalhar/idlista/{$idlista}/pagina/{$btn['previous']}",
        'next' => "{$controllerName}detalhar/idlista/{$idlista}/pagina/{$btn['next']}",
        'current' => "{$controllerName}detalhar/idlista/{$idlista}/pagina/" . Pagination::CURRENT_PAGE
    ];
});

?>
<div class="modal fade" id="modalSuppliersDetails" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Informações do Fornecedor</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <strong>
                    Nome:
                </strong>
                <?= $this->view->resultSolicitacao['suppliers_name']; ?>
                <br>
                <strong>
                    CNPJ:
                </strong>
                <?= $this->view->resultSolicitacao['suppliers_cnpj']; ?>
                <br>
                <strong>
                    Dados:
                </strong>
                <br>
                <?= $this->view->resultSolicitacao['suppliers_details']; ?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" data-dismiss="modal">Ok</button>
            </div>
        </div>
    </div>
</div>
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5>Itens da Solicitação</h5>
                <?php if (isset($this->view->resultLicitacao['number'])) : ?>
                    <div class="alert alert-info" role="alert">
                        Licitação: <strong><?= $this->view->resultLicitacao['number']; ?></strong><br>
                        Órgão: <strong><?= $this->view->resultLicitacao['uasg']; ?> - <?= $this->view->resultLicitacao['uasg_name']; ?></strong><br>
                        Fornecedor:
                        <strong>
                            <?= $this->view->resultSolicitacao['suppliers_cnpj']; ?>
                            - <?= $this->view->resultSolicitacao['suppliers_name']; ?>
                        </strong>
                        (<a href="#" class="text-danger" data-toggle="modal" data-target="#modalSuppliersDetails">
                            mais detalhes
                        </a>)
                        <br>
                        OM:
                        <strong>
                            <?= $this->view->resultSolicitacao['naval_indicative']; ?>
                        </strong>
                        <br>
                        NF:
                        <strong>
                            <?= ($this->view->resultSolicitacao['invoice'] != 'S/N') ? $this->view->resultSolicitacao['invoice'] : '-' ?>
                        </strong>
                        <br>
                        Solicitação:
                        <strong>
                            <?= $this->view->resultSolicitacao['number']; ?>
                            - <?= $this->view->resultSolicitacao['status']; ?>
                        </strong>
                        <?php if ($this->view->resultSolicitacao['reason_action'] && in_array($this->view->resultSolicitacao['status'], ['REJEITADO', 'CANCELADO'])) : ?>
                            <br>
                            Motivo:
                            <strong>
                                <?= $this->view->resultSolicitacao['reason_action']; ?>
                            </strong>
                        <?php endif; ?>
                        <?php if ($this->view->resultSolicitacao['complement']) : ?>
                            <br>
                            Observações do pedido:
                            <strong>
                                <?= $this->view->resultSolicitacao['complement']; ?>
                            </strong>
                        <?php endif; ?>
                        <?php if ($this->view->resultSolicitacao['observation']) : ?>
                            <br>
                            Observações do recebimento:
                            <strong>
                                <?= $this->view->resultSolicitacao['observation']; ?>
                            </strong>
                        <?php endif; ?>
                        <br>
                        Modalidade:
                        <strong>
                            <?= $this->view->resultSolicitacao['modality']; ?>
                        </strong>
                        <br>
                        Finalidade:
                        <strong>
                            <?= $this->view->resultSolicitacao['purposes']; ?>
                        </strong>
                        <br>
                        Tipo de Empenho:
                        <strong>
                            <?= $this->view->resultSolicitacao['types_invoices']; ?>
                        </strong>
                    </div>
                <?php else : ?>
                    <div class="alert alert-info" role="alert">
                        <h4>NÃO LICITADO</h4>
                        Fornecedor:
                        <strong>
                            <?= $this->view->resultSolicitacao['suppliers_cnpj']; ?>
                            - <?= $this->view->resultSolicitacao['suppliers_name']; ?>
                        </strong>
                        (<a href="#" class="text-danger" data-toggle="modal" data-target="#modalSuppliersDetails">
                            mais detalhes
                        </a>)
                        <br>
                        Solicitação:
                        <strong>
                            <?= $this->view->resultSolicitacao['number']; ?>
                            - <?= $this->view->resultSolicitacao['status']; ?>
                        </strong>
                    </div>
                <?php endif; ?>
                <?php
                $ruleCredit = ($this->view->totalSolicitacao['total'] > $this->view->credito['value']);
                if (in_array($this->view->userLoggedIn['level'], ['ADMINISTRADOR', 'ENCARREGADO']) && $this->view->resultSolicitacao['status'] == 'ENCAMINHADO' && isset($this->view->resultLicitacao['number'])) : ?>
                    <div class="alerta-credito">
                        <div class="alert alert-warning" role="alert">
                            O saldo do crédito <strong>disponível</strong> atualmente é de <strong><?= View::floatToMoney($this->view->credito['value']) ?></strong>.<br>
                            O crédito está <strong>comprometido</strong> com o valor de <strong><?= View::floatToMoney($this->view->creditoComprometido['sum_value']) ?></strong>.<br>
                            O valor total da sua <strong>solicitação</strong> é de <strong><?= View::floatToMoney($this->view->totalSolicitacao['total']) ?></strong><br><br>
                            <?php if ($ruleCredit) : ?>
                                <strong>O Crédito disponível é INSUFICIENTE para essa solicitação de Gêneros</strong><br>
                            <?php else : ?>
                                <strong>O Crédito disponível é SUFICIENTE para essa solicitação de Gêneros</strong><br>
                            <?php endif; ?>
                        </div>
                    </div>
                    <div class="alerta-item">
                        <div class="alert alert-danger" role="alert">
                            <?php
                            $ruleQuantity = true;
                            foreach ($this->view->result as $value) :
                                if ($value['quantity'] <= $value['quantity_available']) {
                                    continue;
                                }
                                $ruleQuantity = false;
                            ?>
                                A quantidade de <?= $value['name'] ?> <strong>disponível</strong> atualmente é de <strong><?= floatval($value['quantity_available']); ?></strong>.<br>
                                A quantidade <strong>solicitada</strong> é de <strong><?= floatval($value['quantity']); ?></strong>.<br><br>
                            <?php endforeach; ?>
                            <?php if ($ruleCredit || !$ruleQuantity) : ?>
                                <strong>Você não pode PROVISIONAR essa solicitação!</strong><br>
                            <?php else : ?>
                                <strong>Você deseja PROVISIONAR essa solicitação?</strong><br>
                                <a href="<?= $this->view->controller; ?>processar/acao/proximo/status/ENCAMINHADO/id/<?= $this->view->idlista; ?>" class="btn btn-success">
                                    <i class="fa fa-check"></i> Sim
                                </a>
                                <a href="<?= $this->view->controller; ?>" class="btn btn-danger">
                                    <i class="fa fa-ban"></i> Não
                                </a>
                            <?php endif; ?>
                        </div>
                    </div>
                <?php endif; ?>
                <?php if (in_array($this->view->userLoggedIn['level'], ['ADMINISTRADOR', 'ENCARREGADO']) && $this->view->resultSolicitacao['status'] == 'ENCAMINHADO' && !isset($this->view->resultLicitacao['number'])) : ?>
                <div class="alerta-item">
                    <div class="alert alert-danger" role="alert">
                        <strong>Você deseja PROVISIONAR essa solicitação?</strong><br>
                        <a href="<?= $this->view->controller; ?>processar/acao/proximo/status/ENCAMINHADO/id/<?= $this->view->idlista; ?>" class="btn btn-success">
                            <i class="fa fa-check"></i> Sim
                        </a>
                        <a href="<?= $this->view->controller; ?>" class="btn btn-danger">
                            <i class="fa fa-ban"></i> Não
                        </a>
                    </div>
                </div>
                <?php endif; ?>

                <a href="<?= $this->view->controller; ?>" class="btn btn-warning pull-right">
                    <i class="fa fa-arrow-left"></i> Voltar
                </a>
                <?php if (in_array($this->view->userLoggedIn['level'], ['ADMINISTRADOR', 'ENCARREGADO', 'NORMAL']) && in_array($this->view->resultSolicitacao['status'], ['ELABORADO', 'REJEITADO'])) : ?>
                    <a href="<?= $this->view->controller; ?>encaminhar/id/<?= $this->view->idlista; ?>" class="btn btn-success pull-right" style="margin-right: 10px;">
                        <i class="fa fa-forward"></i> Encaminhar
                    </a>
                <?php endif; ?>
                <?php if (in_array($this->view->userLoggedIn['level'], ['ADMINISTRADOR', 'ENCARREGADO', 'NORMAL']) && $this->view->resultSolicitacao['status'] == 'ABERTO' && !isset($this->view->resultLicitacao['number'])) : ?>
                    <a href="<?= $this->view->controller; ?>adicionararquivo/idlista/<?= $this->view->idlista; ?>" class="btn btn-info pull-right" style="margin-right: 10px;">
                        <i class="fa fa-file"></i> Adicionar arquivo
                    </a>
                <?php endif; ?>
                <?php if (!in_array($this->view->resultSolicitacao['status'], ['ELABORADO', 'REJEITADO', 'CANCELADO'])) : ?>
                    <a href="<?= $this->view->controller; ?>presolemp/id/<?= $this->view->resultSolicitacao['id'] ?>" class="btn btn-secondary" target="__blank">
                        <i class="fa fa-file-pdf-o"></i> Documento SOLEMP DE GÊNEROS
                    </a>
                <?php endif; ?>
                <?php if (!isset($this->view->resultLicitacao['number'])) : ?>
                    <table class="table table-hover table-bordered" style="margin-top: 10px;">
                        <thead>
                            <tr>
                                <th colspan="2">
                                    Arquivos
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach (View::listFilesPdf($fullPathUploadFiles) as $file) : ?>
                                <tr>
                                    <td>
                                        <a href="<?= $relativePathUploadFiles . $file ?>" target="_blank">
                                            Arquivo <?= $file; ?>
                                        </a>
                                    </td>
                                    <td width="8%">
                                        <?php if ($this->view->resultSolicitacao['status'] == 'ABERTO') : ?>
                                            <a onclick="confirmar('Deseja REMOVER este arquivo?', '<?= $this->view->controller; ?>eliminararquivo/file/<?= $file; ?>/idlista/<?= $this->view->idlista; ?>')" class="btn btn-danger btn-sm">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        <?php endif; ?>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                <?php endif; ?>
                <div class="row" style="margin-bottom: 10px; margin-top: 10px;">
                    <div class="col-md-12">
                        <i class="fa fa-list"></i> <?= $this->view->title; ?>
                    </div>
                </div>
                <?= $pagination; ?>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Item</th>
                            <th>Solicitado</th>
                            <th>Entregue</th>
                            <th>Disponível</th>
                            <th>UF</th>
                            <th>Nome</th>
                            <th>Valor (R$)</th>
                            <th>Subtotal (R$)</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $total = 0;
                        $btnDelete = (count($this->view->result) > 1 ? true : false);
                        foreach ($this->view->result as $value) :
                            $total += $value['value'] * $value['quantity'];
                        ?>
                            <tr>
                                <td><?= $value['number'] ?: '-'; ?></td>
                                <td><?= floatval($value['quantity']); ?></td>
                                <td><?= intval($value['delivered']); ?></td>
                                <td><?= floatval($value['quantity_available']); ?></td>
                                <td><?= $value['uf']; ?></td>
                                <td><?= $value['name']; ?></td>
                                <td><?= Utils::floatToMoney($value['value']); ?></td>
                                <td><?= Utils::floatToMoney(($value['value'] * $value['quantity'])); ?></td>
                                <td>
                                    <?php if ($this->view->userLoggedIn['level'] != 'CONTROLADOR' && in_array($this->view->resultSolicitacao['status'], ['REJEITADO', 'ELABORADO'])) : ?>
                                        <a href="<?= $this->view->controller; ?>editar/id/<?= $value['id']; ?>/idlista/<?= $this->view->idlista; ?>" class="btn btn-success btn-sm">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                        <?php if ($btnDelete) : ?>
                                            <a onclick="confirmar('Deseja REMOVER este registro?', '<?= $this->view->controller; ?>eliminaritem/id/<?= $value['id']; ?>/idlista/<?= $this->view->idlista; ?>')" class="btn btn-danger btn-sm">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                    <tfoot>
                        <tr>
                            <th class="text-right" colspan="7">Total (R$)</th>
                            <td class="text-left">
                                <?= Utils::floatToMoney($total); ?>
                            </td>
                        </tr>
                    </tfoot>
                </table>
                <?= $pagination; ?>
            </div>
        </div>
    </div>
</div>
<style>
    .btn-pre-solemp {
        margin-left: 10px;
        margin-right: 10px;
    }
</style>