<?php

use App\Config\Configurations as cfg;
use App\Helpers\View;
use App\Helpers\Utils;

setlocale(LC_TIME, 'pt_BR', 'pt_BR.utf-8', 'pt_BR.utf-8', 'portuguese');
date_default_timezone_set(cfg::TIMEZONE);

$total = 0;

?>
<style>
    body {
        font-size: 12px !important;
        background-color: #fff !important;
    }

    .table-striped>tbody>tr:nth-of-type(2n+1) {
        background-color: #ccc !important;
    }

    .table-print {
        width: 100%;
        border-collapse: collapse;
        margin: 0px auto;
        text-align: center;
    }

    .table-info {
        width: 100%;
        margin-bottom: 20px;
        margin-top: 10px;
    }

    .table-info>tbody>tr>td {
        padding: 8px;
        vertical-align: top;
    }

    .table-condensed>tfoot>tr>td {
        padding: 2px !important;
    }

    .right {
        text-align: right !important;
    }

    .left {
        text-align: left !important;
    }

    .brasao {
        width: 90px;
    }

    .cabecalho {
        font-weight: bold;
    }

    .data-impressao {
        padding-top: 20px;
        padding-bottom: 20px;
    }

    .informacoes span {
        font-weight: bold;
    }

    .finalidade {
        margin-bottom: 10px;
    }

    .width-5-percent {
        width: 5%;
    }

    .width-8-percent {
        width: 8%;
    }

    .width-10-percent {
        width: 10%;
    }

    .text-normal {
        text-transform: none !important;
        font-weight: normal !important;
    }

    .assinaturas {
        padding-top: 50px;
        width: 33%;
    }

    .content-assinatura {
        width: 100%;
        display: block;
        text-align: center;
    }

    .linha-assinatura {
        border-top: 2px solid;
        width: 75%;
        margin: 0px auto;
    }

    .watermark {
        position: absolute;
        opacity: 0.4;
        font-size: 90px;
        color: BLACK;
        bottom: 25%;
        right: 25%;
        transform: rotate(-45deg);
    }
</style>
<?php if ($this->getParametro('watermark')): ?>
<p class="watermark"><?= $this->view->resultSolicitacao['status']; ?></p>
<?php endif; ?>
<table class="table-print">
    <tr>
        <td>
            <img src="images/brasao.png" class="brasao">
        </td>
    </tr>
    <tr>
        <td class="cabecalho text-uppercase">
            MARINHA DO BRASIL
            <br>
            <?= $this->view->resultOm['name']; ?>
            <br>
            <br>
            Solicitação de Empenho (SOLEMP) -
            Nº <?= $this->view->resultSolicitacao['number']; ?>
        </td>
    </tr>
    <tr>
        <td class="tabela-informacoes">
            <table class="table-info">
                <tr rowspan="2">
                    <td class="informacoes left">
                        <span>Fornecedor:</span>
                        <?= $this->view->resultSolicitacao['suppliers_name']; ?>
                    </td>
                </tr>
                <tr>
                    <td class="informacoes left">
                        <span>CNPJ:</span>
                        <?= $this->view->resultSolicitacao['suppliers_cnpj']; ?>
                    </td>
                    <td class="informacoes right">
                        <span>Detalhes da empresa:</span>
                        <?= $this->view->resultSolicitacao['suppliers_details']; ?>
                    </td>
                </tr>
                <tr>
                    <td class="informacoes left">
                        <span>Tipo de Empenho:</span>
                        <span class="tipo_empenho text-normal">
                            <?= $this->view->resultSolicitacao['types_invoices'] ?>
                        </span>
                    </td>
                    <?php if (isset($this->view->resultLicitacao['number'])) : ?>
                        <td class="informacoes right text-uppercase">
                            <span>UASG Licitação:</span>
                            <?= $this->view->resultLicitacao['uasg']; ?> - <?= $this->view->resultLicitacao['uasg_name']; ?>
                        </td>
                    <?php else : ?>
                        <td class="informacoes right text-uppercase">
                            <span>Licitação: NÃO LICITADO</span>
                        </td>
                    <?php endif; ?>
                </tr>
                <tr>
                    <?php if (isset($this->view->resultLicitacao['number'])) : ?>
                        <td class="informacoes left">
                            <span>NR Processo:</span>
                            <?= $this->view->resultLicitacao['number']; ?>
                        </td>
                    <?php else : ?>
                        <td class="informacoes left text-uppercase">
                            <span>Licitação: NÃO LICITADO</span>
                        </td>
                    <?php endif; ?>
                    <td class="informacoes right">
                        <span>Data da Solemp:</span>
                        <?= cfg::htrFileConfigs()->papeleta->cidade ?? '' ?>, <?= date('d/m/Y', strtotime('today')); ?>
                    </td>
                </tr>
                <tr>
                    <td class="informacoes left">
                        <span>Modalidade:</span>
                        <span class="modalidade text-normal">
                            <?= $this->view->resultSolicitacao['modality'] ?>
                        </span>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td class="tabela-informacoes">
            <table class="table table-striped table-hover table-condensed" border="1">
                <thead>
                    <tr>
                        <th class="text-center width-5-percent">
                            UG
                        </th>
                        <th class="text-center width-8-percent">
                            PTRES
                        </th>
                        <th class="text-center width-10-percent">
                            AI
                        </th>
                        <th class="text-center width-5-percent">
                            DO
                        </th>
                        <th class="text-center width-5-percent">
                            BI
                        </th>
                        <th class="text-center width-5-percent">
                            FR
                        </th>
                        <th class="text-center width-10-percent">
                            ND
                        </th>
                        <th class="text-center width-10-percent">
                            Plano de Contas
                        </th>
                    </tr>
                    <tr>
                        <td class="ug text-uppercase">
                            <?= $this->view->resultOm['ug'] ?>
                        </td>
                        <td class="ptres text-uppercase">
                            <?= $this->view->resultOm['ptres'] ?>
                        </td>
                        <td class="ai text-uppercase">
                            <?= $this->view->resultOm['ai'] ?>
                        </td>
                        <td class="do text-uppercase">
                            <?= $this->view->resultOm['do'] ?>
                        </td>
                        <td class="bi text-uppercase">
                            <?= $this->view->resultOm['bi'] ?>
                        </td>
                        <td class="fr text-uppercase">
                            <?= $this->view->resultOm['fr'] ?>
                        </td>
                        <td class="nd text-uppercase">
                            <?= $this->view->resultOm['nd'] ?>
                        </td>
                        <td class="plano_contas text-uppercase">
                            <?= $this->view->resultSolicitacao['account_plan'] ?>
                        </td>
                    </tr>
                </thead>
            </table>
        </td>
    </tr>
    <tr>
        <td class="tabela-itens">
            <table class="table table-striped table-hover table-condensed" border="1">
                <thead>
                    <tr>
                        <th class="text-center width-10-percent">Clasificação Item</th>
                        <th class="text-center width-10-percent">Centro de Custo</th>
                        <th class="text-center width-8-percent">Nº item</th>
                        <th>Descrição</th>
                        <th class="text-center width-8-percent">UF</th>
                        <th class="text-center width-8-percent">Qtd</th>
                        <th class="text-center width-10-percent">Preço Unit.</th>
                        <th class="text-center width-10-percent">Total por Item</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->view->result as $value) : ?>
                        <?php
                        $totaItem = $value['quantity'] * $value['value'];
                        $total += $totaItem;

                        ?>
                        <tr>
                            <td><?= $this->view->resultOm['classification_items'] ?: ''; ?></td>
                            <td><?= $this->view->resultOm['cost_center']; ?></td>
                            <td><?= $value['number'] ?: ''; ?></td>
                            <td class="left"><?= $value['name']; ?></td>
                            <td><?= $value['uf']; ?></td>
                            <td><?= View::floatToMoney($value['quantity'], ''); ?></td>
                            <td><?= View::floatToMoney($value['value'], ''); ?></td>
                            <td><?= View::floatToMoney($totaItem, ''); ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="7" class="right">Total da SOLEMP</td>
                        <td><?= View::floatToMoney($total, ''); ?></td>
                    </tr>
                </tfoot>
            </table>
        </td>
    </tr>
    <tr>
        <td class="informacoes left">
            <span>
                Finalidade/Aplicação:
            </span>
            <?= $this->view->resultSolicitacao['purposes'] ?>
        </td>
    </tr>
    <tr>
        <td class="tabela-informacoes">
            <table class="table table-hover table-condensed" border="1">
                <thead>
                    <tr>
                        <th class="text-center width-5-percent">Ação</th>
                        <th class="text-center width-5-percent">NIP Usuário</th>
                        <th class="text-center width-5-percent">Nome Usuário</th>
                        <th class="text-center width-5-percent">Data/Hora da Ação</th>
                        <th class="text-center width-5-percent">Perfil Usuário</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->view->acoes as $value) : ?>
                        <tr>
                            <td><?= $value['action'] ?: ''; ?></td>
                            <td><?= $value['nip'] ?: ''; ?></td>
                            <td><?= $value['user_name'] ?: ''; ?></td>
                            <td><?= date('d-m-Y H:i:s', strtotime($value['date_action'])); ?></td>
                            <td><?= $value['user_profile'] ?: ''; ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
                <tfoot></tfoot>
            </table>
        </td>
    </tr>
</table>