<?php

use App\Helpers\Pagination;
use App\Helpers\View;

$pagination = Pagination::make($this);

?>
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5>Organizações Militares</h5>
                <i class="fa fa-list"></i> <?= $this->view->title; ?><br>
                <a href="<?= $this->view->controller; ?>novo/" class="btn btn-info">
                    <i class="fa fa-plus-circle"></i> Novo Registro
                </a>
                <div class="row">
                    <div class="col-md-7">
                        <?= $pagination; ?>
                    </div>
                    <div class="col-lg-5">
                        <form action="#" class="search-form" onsubmit="return false">
                            <div class="input-group search-input-box">
                                <input type="text" class="form-control search-input" placeholder="UASG, Nome ou Ind. Naval">
                                <span class="input-group-btn">
                                    <button class="btn btn-secondary search-button" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                        </form>
                    </div>
                </div>
                <table class="table">
                    <thead>
                        <tr>
                            <th>UASG</th>
                            <th>Nome</th>
                            <th>Ind. Naval</th>
                            <th>Atualização</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->result as $value): ?>
                            <tr>
                                <td><?= $value['uasg']; ?></td>
                                <td><?= $value['name']; ?></td>
                                <td><?= $value['naval_indicative']; ?></td>
                                <td><?= View::humanDate($value['updated_at']); ?></td>
                                <td>
                                    <a href="<?= $this->view->controller; ?>editar/id/<?= $value['id']; ?>" class="btn btn-success btn-sm">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                    <a
                                       onclick="confirmar('Deseja REMOVER este registro?', '<?= $this->view->controller; ?>eliminar/id/<?= $value['id']; ?>')"
                                       class="btn btn-danger btn-sm">
                                        <i class="fa fa-trash"></i>
                                    </a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <?= $pagination; ?>
            </div>
        </div>
    </div>
</div>
<script>
    $('.search-button').click(function() {
        btnSearch();
    });
    $('.search-input').keypress(function(event){
        var keycode = (event.keyCode ? event.keyCode : event.which);
        if(keycode == '13') {
            btnSearch();
        }
    });
    function btnSearch() {
        var searchInput = $('.search-input');
        var searchValue = searchInput.val();
        var url = 'om/ver/';
        if (searchValue && url) {
            window.location = url + 'busca/' + searchValue;
        } else {
            searchInput.focus();
        }
    }
</script>